### ISSUE TITLE
"Custom Field : Dropdown list of centres. Filter Centres by City."

### ISSUE THREAD

**Issue by revant** [gaurav-naik/awfis_erpnext#11]
**DocType:** Sales Order
**Field:** Centre
**ERPNext Default:** -
**Customization:** 
"Custom Field : Dropdown list of centres.
Filter Centres by City."

**Comment by gaurav-naik** [comment]
https://github.com/gaurav-naik/awfis_erpnext/commit/e36f7a2e3d18b2f9767d81bd84fc9587bace0b81
