### ISSUE TITLE
Role Permission for Awfis Center

### ISSUE THREAD

**Issue by revant** [gaurav-naik/awfis_erpnext#12]
Currently Awfis Centre DocType is only allowed for Administrator

Remove Administrator altogether because on production environment Admin is not used.

Select from existing other role or create new role under awfis_erpnext

**Comment by gaurav-naik** [comment]
https://github.com/gaurav-naik/awfis_erpnext/commit/4d0f96ba014b514f25222b029b78a7db466d400c
