### ISSUE TITLE
Follow the order of fields

### ISSUE THREAD

**Issue by revant** [gaurav-naik/awfis_erpnext#14]
Please follow the same order of fields as they are mentioned in the document shared. e.g. in Lead Module, City and Centre should come on top instead of in Contact & Add section

**Comment by gaurav-naik** [comment]
City and Centre have been moved to Opportunity https://github.com/gaurav-naik/awfis_erpnext/commit/c9304b178839508caa4cfaefd3d29865a9e1ef88
**Reason :** The same lead may yield multiple opportunities. Each opportunity can be for a different Centre.

**Comment by gaurav-naik** [comment]
Added custom fields and scripts as a workaround to reordering restrictions. Lead Source, being an important native field with dependent logic, was not included in this workaround. https://github.com/gaurav-naik/awfis_erpnext/commit/e1a5a900791d841099c04eb556fe8259847d7247

**Comment by gaurav-naik** [comment]
Where should the Territory field (currently under the Address and Contact section) be placed on the Lead form?

**Comment by preranamergu** [comment]
It is a rare scenario where one lead will be assigned to different centres. However, to tackle this situation, we can create multiple selection criteria for centre (where one can select more than one centre for lead). 
It is important to keep city and centre fields for Leads. Because not all leads will be converted into opportunity and we need to track each and every lead coming for each centre.

**Comment by revant** [comment]
In ERPNext Lead can have multiple opportunities:

Eg. 
- Mr. ABC, of XYZ Ltd from Sales Territory Mumbai is a Lead
- If Mr. ABC asks for Service in Delhi > Create opportunity for Delhi Centre from the Lead.
- If Mr. ABC asks for Service in Bangalore > Create another opportunity for Bangalore Centre from the same Lead.
- Centre-wise Opportunities (Cases) can be created.
- Opportunities can be lost and reason can be set.

Once the Lead Orders, It becomes a Customer (Account) in ERPNext.
Customer can have multiple opportunities as well.

**Comment by revant** [comment]
Re ordered Fields of Customer (Account)
https://github.com/gaurav-naik/awfis_erpnext/commit/acd4d8b587e09c09618f67f1c1c0fb28c0fa8f17

To Reorder :  
- [x] Contact
- [ ] Sales Order
- [x] Channel Partners

**Comment by revant** [comment]
Re ordered Fields of Sales Partner (Channel Partner)
https://github.com/gaurav-naik/awfis_erpnext/commit/a6d9b9694966a62a3b1a4431ad10cafe9179fde5

**Comment by revant** [comment]
@vickybiswas @preranamergu 
Logging a note

Frappe Framework does not allow Re-arranging of forms. Only Custom Fields can be rearranged.
reference : https://frappe.io/blog/erpnext-features/rearranging-forms

Right now all the rearrangement is happening by:
1. Create a Custom Field and place it where required e.g. fieldname: awfis_mobile_no
2. Hide ERPNext Default Field and make it Read-only. This field is to be rearranged e.g. fieldname: mobile_no
3. On entering Data in this Custom Field (awfis_mobile_no) it is copied by custom javascript in the default ERPNext field (mobile_no)
4. ERPNext fields are kept read only and also hidden if it is in the non arranged view.

This Partly voilates DRY Principle

**Comment by gaurav-naik** [comment]
Added and re-ordered Fields in Sales Order. https://github.com/gaurav-naik/awfis_erpnext/commit/733950471e8b323e153be04a6b3c8076d105c7d1
