### ISSUE TITLE
Follow the nomenclature 

### ISSUE THREAD

**Issue by revant** [gaurav-naik/awfis_erpnext#15]
Please follow the same nomenclature of the fields/ options as in the document. So that it is in sync with the terminology used internally.

**Comment by gaurav-naik** [comment]
Some options in Select fields cannot be changed because logic native to ERPNext depends directly on them.
Options without dependent logic will be identified and changed as per the requirements.

**Comment by preranamergu** [comment]
Is there a way to keeping the same option and changing the text? E.g. in Lead Status, "Do Not Contact" can be renamed as "Lost Lead"

**Comment by revant** [comment]
ERPNext Sales Funnel Report is using this specific text "Do Not Contact". The change will affect the report.

https://github.com/frappe/erpnext/blob/develop/erpnext/selling/page/sales_funnel/sales_funnel.py#L13
