### ISSUE TITLE
Add City in Leads

### ISSUE THREAD

**Issue by revant** [gaurav-naik/awfis_erpnext#2]
**DocType:** Lead
**Field:** City
**ERPNext Default:** Use Territory DocType. Filter list to ensure that only leaf nodes are displayed.
**Customization:** Custom Field for linking City to Lead. Filter Centres by City"

**Comment by gaurav-naik** [comment]
Done. Added in develop branch.

**Comment by revant** [comment]
https://github.com/gaurav-naik/awfis_erpnext/commit/8b1cc7c82ed96e0f45c85d1ca9dfa629eeac2285
