### ISSUE TITLE
Please remove the option 'Lead' from Lead Status

### ISSUE THREAD

**Issue by preranamergu** [gaurav-naik/awfis_erpnext#20]

**Comment by revant** [comment]
There seems to be no connection with Lead Status "Lead" only that it is set as default for every new lead created.

Default for new lead will be set to "Open".

**Comment by preranamergu** [comment]
In that case, please remove that option. You can put 'Open' as default option.

**Comment by revant** [comment]
Removed 
https://github.com/gaurav-naik/awfis_erpnext/commit/71919ed38862cee319d7f076797d34f385a82a7e
