### ISSUE TITLE
Channel in Opportunity

### ISSUE THREAD

**Issue by preranamergu** [gaurav-naik/awfis_erpnext#21]
The channel in opportunity should be fetch directly from Lead module. 
Also, currently not all options are visible for Channels in Opportunity.

**Comment by revant** [comment]
Lead Sources listed in The requirement Docx shared are more than the channel for Opportunity (Case)

Lead Source (REQUIRED)
i. Broker 
ii. IPC
iii. Searched on Google
iv. Social Media
v. Online Listing
vi. E-mail marketing
vii. Events or Seminars
viii. Reference
ix. Outdoor hoardings/ Banners/ signage outside Awfis centres
x. Other

Channel (REQUIRED)
a. Call Centre
b. Walk-in (Potential customers)
c. In-centre Feedback (Existing customers)
d. contact@awfis.com
e. Social Media
f. Other

So it cannot be copied 1 : 1

**Comment by preranamergu** [comment]
'Opportunity' and 'Cases' are two different modules altogether as discussed over phone last time.
'Opportunity' is a subset of 'Leads', whereas 'Cases' can be queries, requirement (which need to be re-directed to Leads) and complaints.
Since 'Opportunity' is a subset of Lead, the source of opportunity will be same as source of Lead.
Cases (Q/R/C), on other hand can be generated through different channels such as Call centre, Walk-in, email etc.
Will call you to discuss in case of any doubt.

**Comment by revant** [comment]
But then Cases as per the discussion yesterday were to be handled via 

CRM > Communication
and 
Support > Issues

**Comment by preranamergu** [comment]
Yes, Then we will add respective fields for Cases under Communication and/or Issues. But not under 'Opportunity'.

**Comment by revant** [comment]
Okay then should the field names "Channel" or "Source" for Issue and Communication

And what are the list of options? Lead Source ones (10) or the Case Channel ones (6)

**Comment by preranamergu** [comment]
Channel (as mentioned in the document)

**Comment by revant** [comment]
https://github.com/gaurav-naik/awfis_erpnext/commit/8d8c5427e8ba48bfaa1e806f581c8052b6cf3cb0

Added Channel to Communication and Issue

Channel cannot be made mandatory in communication as it is used by Frappe Framework and if it is made mandatory Sending email of any Doctype stops working

Channel is made mandatory in Issue

Issue can be tracked for Lead as well as Customer in ERPNext
