### ISSUE TITLE
Hide the fields that are not relevant

### ISSUE THREAD

**Issue by preranamergu** [gaurav-naik/awfis_erpnext#22]
Please hide the fields in the respective modules that are not mentioned in the document (that are not relevant). It may just add the confusion for the team while filling the data.

E.g. Supplier, Sales Partner in 'Contacts'; TaxID, customer group in 'Customers' etc.

Please follow the same for all modules.

**Comment by revant** [comment]
Supplier, Sales Partner also have contacts in ERPNext

If you are planning to use Purchase Module of ERPNext, Contacts of the Supplier's Company are also Stored under Contacts.

Sales Partner Module is Part of ERPNext which can be for Channel Partner and Paying commissions.

Channel Partner Company / Organization also requires to store contacts

Hiding of the fields can be done on installed system by "System Manager" users.

Setup > Customize > Customize Form 
Select Form for which you wish to hide fields e.g. "Customer"
Hide TaxID

Customer Group is required by ERPNext:
Will have to Set a default Customer group for all customer and hide it then.

**Comment by revant** [comment]
Role based permissions will handle this

**Comment by preranamergu** [comment]
Still can see many fields which are yet to be hidden. 

e.g. Department, Designation, Supplier, Sales Partner in Contact

Customer group in Accounts etc.

**Comment by revant** [comment]
- [x] Filter Territory for is_group : 1
  https://github.com/gaurav-naik/awfis_erpnext/commit/6ea4550231647828ed7d928feb93be4f1b907d3c

**Comment by preranamergu** [comment]
Please find below the list of Fields to be hidden

Lead:
- [x] Market Segment
- [x] Request Type
- [ ] Unsubscribed
- [x] Blog Subscriber

Opportunity:
- [x] Type of Case
- [ ] Opportunity From
- [x] Customer
- [x] Subject
- [x] Description
- [x] Resolution
- [x] Customer Group
- [ ] Company- Awfis Space Solutions

Customer:
- [ ] Customer Group
- [x] Tax ID
- [x] Billing Currency
- [ ] Print Language
- [x] Default Price List

Contact:
- [ ] Status
- [x] Phone

**Comment by gaurav-naik** [comment]
Fields unchecked in the list above could not be hidden because they were either mandatory or had dependent logic.

**Comment by gaurav-naik** [comment]
Closed after successful resolution on conference call. @vickybiswas  @preranamergu  @revant @RajivNaik
