### ISSUE TITLE
Link Territory to Centre 

### ISSUE THREAD

**Issue by preranamergu** [gaurav-naik/awfis_erpnext#23]
Please link territory to centre such as If selected Mumbai, the centres shown should include Churchgate, Andheri W, Powai, Lower Parel etc. No centres from Delhi and Bangalore should be shown.

**Comment by revant** [comment]
Linked Territory to Centre
https://github.com/gaurav-naik/awfis_erpnext/commit/2290192b86b549c17e078d5e2ca4a08b5cc8cac4

**Comment by preranamergu** [comment]
Kindly add all the Cities and Centre mentioned in the document. 
Any addition to the centre/ city, we will add it from our end. 

Also remove all the other options- All India, All Territories, Rest of the World etc.

**Comment by revant** [comment]
Add Territories in 
Selling > Sales Partners and Territory > Territory 

Add Centres in

Awfis Erpnext > Setup > Awfis Centre
