### ISSUE TITLE
Please add requirements in Lead module

### ISSUE THREAD

**Issue by preranamergu** [gaurav-naik/awfis_erpnext#24]
Kindly add requirement in Lead Module as below:

Type of Space:
1. Cabin
2. Fixed Seat
3. Flexi Seat
4. Meeting Room

Number of seats: 
1. Cabin __________
2. Fixed Seat _______
3. Flexi Seat ________
4. Meeting Room _______ Seater

Tenure:
1. Years ________
2. Months _______
3. Weeks _______
4. Days ________
5. Hours _______

**Comment by revant** [comment]
- [ ] Add with item and Item list to lead

**Comment by gaurav-naik** [comment]
Recommend adding these features in the Call Centre module.

**Comment by preranamergu** [comment]
We need to capture these details for all the leads and not just for those coming from call centre channel

**Comment by gaurav-naik** [comment]
Closed after successful resolution on conference call. @vickybiswas @preranamergu @revant @RajivNaik
