### ISSUE TITLE
Additional Fields in Contact

### ISSUE THREAD

**Issue by preranamergu** [gaurav-naik/awfis_erpnext#25]
Please add below fields in Contact:
1. Date of Birth
2. Date of Anniversary 
3. Pan Card number (Only for contacts under customers)
4. Joining Date (Only for contacts under customers)

**Comment by gaurav-naik** [comment]
Done https://github.com/gaurav-naik/awfis_erpnext/commit/1c457a16fa884c160ba17d267ebd46c42500921f
