### ISSUE TITLE
Change in the Channel Field

### ISSUE THREAD

**Issue by preranamergu** [gaurav-naik/awfis_erpnext#26]
in Lead, please add below field:

Lead Channel:
1. Sales Team
2. Call Centre
3. Centre Walk-in

Kindly fetch the same in opportunity as well.

Please keep the Channel list in Issue unchanged.

**Comment by gaurav-naik** [comment]
Done https://github.com/gaurav-naik/awfis_erpnext/commit/c97452f9a493fc429def660a73e1aa2b339ab55c

**Comment by vickybiswas** [comment]
Channel incorrectly added
It is not a requirement

**Comment by gaurav-naik** [comment]
Old channel field dropped from Opportunity. Channels now in Lead Channel field. https://github.com/gaurav-naik/awfis_erpnext/commit/608a68c0c27d4f7d7d8969c04099f94d623632bb
