### ISSUE TITLE
Pull Centres from Lead to Opportunity

### ISSUE THREAD

**Issue by gaurav-naik** [gaurav-naik/awfis_erpnext#29]
**Requirement:**
Centres selected in Lead need to be tracked at Opportunity level.

**Tasks:** 
1. Custom field for storing Centres in Opportunity.
2. Custom script for populating Centres from Lead.

**Completed**: 1.5 hrs

@vickybiswas

**Comment by revant** [comment]
@gaurav-naik will release for production
