### ISSUE TITLE
Opportunity, PI System and Accounting: Links

### ISSUE THREAD

**Issue by gaurav-naik** [gaurav-naik/awfis_erpnext#32]
@vickybiswas @preranamergu 

@revant @riddhimaan

Based on our discussions in the past weeks, changes proposed in the Opportunity module are as follows:
1. **Linking opportunity with PI:**
   - On Opportunity form we can provide a 'PI no' field to link opportunity with PI.
2. **Creating sales invoices from converted opportunities:**
   - On Opportunity form we can provide a button to create sales invoices for Accounts dept from converted opportunities.

**ETA**: 5 hrs.

Pl. let us know if you need any clarification, have suggestions or if we may proceed with development based on this plan.

**Comment by vickybiswas** [comment]
Guys,

Lets Understand what goes where

ERPNext                                      | Awfis system
Opportunity                                  | 
PI No                                            | PI
Sales                                            | Invoice
Total Amount & Invoice Number  |

and now Replan this ticket

**Comment by gaurav-naik** [comment]
Your post apparently reiterates the separation of systems discussed during our Powai meeting. Here is what we have inferred from it:

| ERPNext | Awfis System |
| :-- | :-- |
| Opportunity | PI No |
|  | PI Sales |
|  | Invoice Total Amt & Invoice No |

Based on this inference, we would revise the ticket as follows:
1. Save **PI No** in **Opportunity**
   1.  Custom field ‘PI No’.
   2. Saving an Opportunity with a filled PI No field will mark it as Converted.
2. Save **Invoice Total Amount & Invoice Number** in **Opportunity**
   1. Custom fields for Invoice Total Amount and Invoice Number.
   2. Amount and No may be:  
      1. Pulled using REST API of PI System on click of a button **OR**
      2. Entered manually with PI No as reference.

**ETA:**
(With REST API): 4.5 hrs.
(Manual entry): 2 hrs.

Please let us know if the inference and the revision are valid. Thanks.

**Comment by vickybiswas** [comment]
The Conversion to Sale should happen on Total Amount and Invoice Number Entry

On PI Entry it is a Prospect

**Comment by gaurav-naik** [comment]
So finally three values will be stored in Opportunity:
PI No, Invoice No and Total Amount.

**Action**: Enter PI No, Save.
**Effect**: Opportunity marked as 'Prospect' (new status)

**Action**: Enter Invoice No, Total Amount, Save.
**Effect**: Opportunity marked as 'Converted'

**ETA**: 2 hrs

Can we proceed with this?

**Comment by vickybiswas** [comment]
These will eventually only be rest endpoints that will be called by other system with email as common data and above fields as data to be altered

Temporarily this can be updated manually however as soon as the new system being developed kicks in this will be done using rest endpoint.

**Comment by gaurav-naik** [comment]
REST API call for setting PI No will look like:

```
[GET] http://{awfis_ip}/api/method/mark_as_prospect?email={email}&pino={pi_no}
```

Fields for manual entry can be made readonly once the new system kicks in.

**Tasks**:
1. Opportunity
   1. Manual Entry
      - Custom fields: PI No, Sales Invoice No and Amount
      - Code to set status as Prospect or Converted depending on values of above fields.
      - New Status: Prospect
   2. REST API
      - Method to set PI No (and status to Prospect)
      - Method to set Sales Invoice No and Total Amt. (and status to Converted) 
2. Lead
   1. Validation: Allow conversion to Opportunity only if EMail ID has been entered. (As EMail ID is the link between ERPNext and Awfis's system)

**ETA**: 4.5 hrs

**Comment by vickybiswas** [comment]
Not to be done this way
