### ISSUE TITLE
Track item requirements at Lead

### ISSUE THREAD

**Issue by gaurav-naik** [gaurav-naik/awfis_erpnext#33]
As discussed with Prerana earlier today, the plan proposed in Issue #32 will not be followed. There will be no links between ERPNext and the PI System for now.

Customer's space requirements will be tracked in Lead. 
Also, Leads will be marked as Converted manually by the Sales team.

**Objective-wise Tasks**
1. Track space requirements in Lead:
   1. Add 'Lead Item' grid in Lead. 
2. Space requirements will include Space Type, Tenure, Capacity and Qty:
   1. Create doctype 'Lead Item' with dropdowns for Space Type, Tenure and Capacity and textfield for Qty

**ETA**: 0.5 hrs

Is this suitable? Suggestions?

@vickybiswas @preranamergu

@revant @riddhimaan

**Comment by vickybiswas** [comment]
Close it today and handover to Prerna
