### ISSUE TITLE
Change the options of Lead Status

### ISSUE THREAD

**Issue by preranamergu** [gaurav-naik/awfis_erpnext#34]
Hi,

Please change the options of Lead Status as below:
1. Open (Default)
2. Follow-up
3. Won
4. Lost
5. Junk Lead

Kindly confirm once done.

Thanks
Prerana

**Comment by revant** [comment]
@preranamergu please check and close the issue

**Comment by preranamergu** [comment]
Checked and confirmed. Thanks.
