### ISSUE TITLE
Knowlarity Integration

### ISSUE THREAD

**Issue by nkanish2002** [gaurav-naik/awfis_erpnext#38]
Hi, while looking for Knowlarity and ERPNext integration, I stumbled upon your GitHub Repository. It would be very kind of you if you could tell me how to install this plugin more specifically the Knowlarity integration.

Thank you!

**Comment by gaurav-naik** [comment]
Hi.

Currently this isn't a generic plugin. It was developed specifically for our client Awfis, and involved to-and-fro with Knowlarity's development team as well as Awfis's call centre team.

Basically, here is how it works: When Knowlarity's server routes a call to the call-centre agent's phone, a popup is displayed on the agent's ERPNext session. In the background, the caller number is looked up in ERPNext's Leads database. For an existing lead, the Lead's name and a link to the Lead form are displayed in the popup.

ERPNext's REST API has been used here. Knowlarity's software calls a custom REST endpoint which looks up the caller number in Leads and renders the popup.

Let me know if you need any additional information.

**Comment by nkanish2002** [comment]
Hi Gaurav, that is exactly what is required by us. Is it possible to create a generic plugin for ERPNext by cherry-picking code from your repository? If so, could you please direct me to the code for Popup notifications? I have already gone through the ERPNext's REST API and I he should be able to provide the call log functionality.
