### ISSUE TITLE
Channel Partner in Lead

### ISSUE THREAD

**Issue by revant** [gaurav-naik/awfis_erpnext#6]
**DocType:** Lead
**Field:** Channel Partner
**ERPNext Default:** Use existing Sales Partner DocType with type Channel Partner
**Customization:** "Add Custom Field Sales Partner. Display if Lead Source = IPC or Broker"

**Comment by gaurav-naik** [comment]
https://github.com/gaurav-naik/awfis_erpnext/commit/8b1cc7c82ed96e0f45c85d1ca9dfa629eeac2285
