### ISSUE TITLE
Dropdown with options Query, Requirement, Complaint  Allow linking of Issue DocType when Case Type = Complaint"

### ISSUE THREAD

**Issue by revant** [gaurav-naik/awfis_erpnext#8]
**DocType:** Opportunity
**Field:** Case Type
**ERPNext Default:** 
**Customization:** 
"Custom Field: Dropdown with options Query, Requirement, Complaint 
Allow linking of Issue DocType when Case Type = Complaint"

**Comment by gaurav-naik** [comment]
https://github.com/gaurav-naik/awfis_erpnext/commit/e36f7a2e3d18b2f9767d81bd84fc9587bace0b81
